### ISSUE TITLE
Conversion of `thetas` to `thetas_ori` for MDM Output

### ISSUE THREAD

**Issue by anhnb206110** [wenj/GoMAvatar#5]
When I run the eval.py script with `--type pose_mdm`, it loads the pose from `data/mdm_poses/sample.npy`. This file contains the key `thetas_ori`. However, when I use MDM (https://github.com/GuyTevet/motion-diffusion-model) to generate a pose from text and save it to `mysamplepose.npy`, the result does not include the `thetas_ori` key, although all other keys are the same between `sample.npy` and `mysamplepose.npy`. How can I convert the `thetas` in MDM's output (with shape (24, 6)) to `thetas_ori` (with shape (24, 3))?

**Comment by wenj** [comment]
My guess is the (24, 6) output represents the angles in rotation 6D and the (24, 3) output uses axis angle. You may try pytorch3D's [rotation_6d_to_matrix](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.rotation_6d_to_matrix) and [matrix_to_axis_angle](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.matrix_to_axis_angle).

**Comment by anhnb206110** [comment]
Thanks for your answer. I followed and it works properly.
